import { BookOpen, GraduationCap, Heart, LogIn, ShieldCheck, Sparkles, UsersRound } from 'lucide-react'

const roles = [
  { key: 'student', title: 'Arday', subtitle: 'Student portal', description: 'Akhri, xifdi, la soco horumarkaaga, oo raac qorshahaaga Quran.', icon: GraduationCap, href: '/login?role=student' },
  { key: 'teacher', title: 'Macalin', subtitle: 'Teacher portal', description: 'Maamul ardayda, casharrada, dib-u-eegista iyo horumarka fasalka.', icon: UsersRound, href: '/login?role=teacher' },
  { key: 'parent', title: 'Waalid', subtitle: 'Parent portal', description: 'La soco horumarka ilmahaaga iyo joogteynta barashada Quran-ka.', icon: ShieldCheck, href: '/login?role=parent' },
]

export default function LandingPage() {
  return <div className="min-h-screen overflow-hidden bg-[#f7faf8] text-slate-900">
    <header className="sticky top-0 z-50 border-b border-slate-200/70 bg-white/85 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><a href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-emerald-700 text-white shadow-lg"><BookOpen size={20}/></span><span><span className="block text-lg font-extrabold">Tarteel</span><span className="hidden text-[10px] font-semibold uppercase tracking-[.18em] text-slate-400 sm:block">Quran learning</span></span></a><a href="/login" className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white hover:bg-slate-800"><LogIn size={16}/> Gal</a></div></header>
    <main>
      <section className="relative overflow-hidden"><div className="pointer-events-none absolute -right-32 -top-32 h-96 w-96 rounded-full bg-emerald-200/50 blur-3xl"/><div className="pointer-events-none absolute -left-40 top-40 h-96 w-96 rounded-full bg-amber-100/70 blur-3xl"/><div className="mx-auto grid max-w-7xl gap-12 px-4 pb-16 pt-14 sm:px-6 sm:pt-20 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:px-8 lg:pb-24"><div className="relative"><div className="inline-flex items-center gap-2 rounded-full border border-emerald-100 bg-white px-3 py-1.5 text-xs font-bold text-emerald-800 shadow-sm"><Sparkles size={14}/> Baro · Akhri · Xifdi · Joogtee</div><h1 className="mt-6 max-w-3xl text-4xl font-black tracking-tight text-slate-950 sm:text-5xl lg:text-6xl lg:leading-[1.08]">Quraanka baro, <span className="text-emerald-700">qalbiga ku hay.</span></h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-600 sm:text-lg">Tarteel waa meel casri ah oo ardayga, macalinka iyo waalidka isku xirta—si akhriska, xifdiga iyo horumarka Quran-ka loogu sameeyo si fudud oo joogto ah.</p><div className="mt-8 flex flex-wrap gap-3"><a href="/mushaf" className="inline-flex items-center gap-2 rounded-2xl bg-emerald-700 px-5 py-3.5 text-sm font-bold text-white shadow-xl hover:bg-emerald-800"><BookOpen size={18}/> Akhri Mushafka</a><a href="#portals" className="inline-flex items-center gap-2 rounded-2xl border border-slate-200 bg-white px-5 py-3.5 text-sm font-bold text-slate-700 shadow-sm"><LogIn size={18}/> Gal portal-kaaga</a></div></div><div className="relative mx-auto w-full max-w-md"><div className="rounded-[2rem] border border-[#d7c9a7] bg-[#fffdf5] p-5 shadow-2xl sm:p-7" dir="rtl"><div className="rounded-2xl border border-[#e1d6bb] bg-[#fffef9] p-6 text-center"><p className="text-xs font-bold tracking-[.22em] text-emerald-700">سُورَةُ الْعَلَقِ</p><p className="mt-5 font-[Amiri,serif] text-3xl leading-[2.1] text-slate-800 sm:text-4xl">اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ</p><div className="mx-auto mt-5 h-px w-20 bg-[#c9b98e]"/><p className="mt-4 text-xs text-slate-400">Madinah Mushaf · Page 597</p></div><div className="mt-4 flex items-center justify-between rounded-2xl bg-emerald-50 px-4 py-3" dir="ltr"><span className="text-xs font-semibold text-emerald-800">Daily reading</span><span className="text-sm font-extrabold text-emerald-900">15 min</span></div></div></div></div></section>
      <section className="mx-auto max-w-7xl px-4 pb-14 sm:px-6 lg:px-8"><div className="grid gap-4 md:grid-cols-2"><div className="rounded-3xl border border-emerald-100 bg-emerald-50 p-6 sm:p-7"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-white text-emerald-700 shadow-sm"><BookOpen size={20}/></span><p className="text-sm font-bold uppercase tracking-wider text-emerald-800">Aayad</p></div><p dir="rtl" lang="ar" className="mt-5 font-[Amiri,serif] text-2xl leading-[2] text-emerald-950">وَقُلْ رَبِّ زِدْنِي عِلْمًا</p><p className="mt-2 text-xs font-semibold text-emerald-700">“Rabbiyow, ii kordhi cilmiga.” — Qur'aan 20:114</p></div><div className="rounded-3xl border border-amber-100 bg-amber-50 p-6 sm:p-7"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-white text-amber-700 shadow-sm"><Heart size={20}/></span><p className="text-sm font-bold uppercase tracking-wider text-amber-800">Xadiis</p></div><p className="mt-5 text-base font-semibold leading-7 text-amber-950">“Khayrkiinna waa kan barta Qur'aanka oo bara.”</p><p className="mt-2 text-xs font-semibold text-amber-700">Saxiix Al-Bukhaari</p></div></div></section>
      <section id="portals" className="border-y border-slate-200/70 bg-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-700">Choose your portal</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl">Qof walba meel u gaar ah</h2><p className="mt-4 text-sm leading-7 text-slate-500">Dooro doorkaaga si aad ugu gasho khibrad ku habboon shaqadaada.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{roles.map(({ key, title, subtitle, description, icon: Icon, href }) => <a key={key} href={href} className="group rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition duration-200 hover:-translate-y-1 hover:border-emerald-200 hover:shadow-xl"><div className="flex items-start justify-between"><span className="grid h-13 w-13 place-items-center rounded-2xl bg-emerald-50 text-emerald-700"><Icon size={24}/></span><span className="rounded-full bg-slate-50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-slate-400">{subtitle}</span></div><h3 className="mt-6 text-xl font-extrabold text-slate-900 group-hover:text-emerald-800">{title}</h3><p className="mt-2 min-h-14 text-sm leading-6 text-slate-500">{description}</p><span className="mt-6 inline-flex text-sm font-bold text-emerald-700">Gal {title} →</span></a>)}</div></div></section>
      <section className="mx-auto max-w-7xl px-4 py-14 text-center sm:px-6 lg:px-8"><p className="text-sm font-semibold text-slate-500">Akhris joogto ah, xifdin qorshaysan iyo waxbarasho la cabbiri karo.</p><div className="mt-5 flex flex-wrap justify-center gap-2 text-xs font-semibold text-slate-500"><span className="rounded-full bg-white px-3 py-2 shadow-sm ring-1 ring-slate-200">Mushaf 604 pages</span><span className="rounded-full bg-white px-3 py-2 shadow-sm ring-1 ring-slate-200">Audio & review</span><span className="rounded-full bg-white px-3 py-2 shadow-sm ring-1 ring-slate-200">Goals & streaks</span><span className="rounded-full bg-white px-3 py-2 shadow-sm ring-1 ring-slate-200">Student · Teacher · Parent</span></div></section>
    </main>
    <footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-2 px-4 py-7 text-center text-xs text-slate-400 sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><span>© {new Date().getFullYear()} Tarteel</span><span>Quran learning with purpose and consistency.</span></div></footer>
  </div>
}
